[package]
name = "cauchy"
version = "0.1.0"
authors = ["Lúcás Meier <cronokirby@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.22.0"
imgui = "0.0.21"
imgui-glium-renderer = "0.0.21"
nom = "4.1.1"
